### ISSUE TITLE
Fails to build with node v10

### ISSUE THREAD

**Issue by tmm1** [mkrufky/node-dvbtee#24] opened 2018-05-23 17:45 UTC
```
  CXX(target) Release/obj.target/dvbtee/src/node-dvbtee.o
  CXX(target) Release/obj.target/dvbtee/src/dvbtee-parser.o
../src/dvbtee-parser.cc:54:37: error: no matching member function for call to 'NewInstance'
    info.GetReturnValue().Set(cons->NewInstance(argc, argv));
                              ~~~~~~^~~~~~~~~~~
/Users/tmm1/.node-gyp/10.1.0/include/node/v8.h:3851:44: note: candidate function not viable: requires
      single argument 'context', but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/tmm1/.node-gyp/10.1.0/include/node/v8.h:3848:44: note: candidate function not viable: requires 3
      arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
1 error generated.
make: *** [Release/obj.target/dvbtee/src/dvbtee-parser.o] Error 1
make: *** Waiting for unfinished jobs....
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/Cellar/node/10.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "-j" "8"
gyp ERR! cwd /private/tmp/node_modules/dvbtee
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by mkrufky** [comment] 2018-05-24 03:57
Thank you, @tmm1 .  This was fixed in https://github.com/mkrufky/node-dvbtee/commit/d791c23259984de7531dfa9b2dbae2694a551995 and released in [v0.3.7](https://github.com/mkrufky/node-dvbtee/releases/tag/v0.3.7) earlier today, so I am closing this.  Please reopen if you're still seeing this problem with the latest build.

**Comment by mkrufky** [comment] 2018-05-24 03:58
also, duplicate of #23

**Closed as completed by mkrufky** 2018-05-24 03:57 UTC

**Comment by tmm1** [comment] 2018-05-24 04:12
Thanks for the quick fix!
